name: Athcraft - Gatekeeper
main: me.CrystalCoding.ServerProtection.AthProtection
version: 1.0
website: athcraft.com
author: Baseball435
description: >
             Allows admins to do different functions.
commands:
  lockdown:
    description: Stops players from logging in.
    usage: |
           /<command>
           Example: /<command>
  stoplockdown:
    description: Allows players to log in.
    usage: |
           /<command>
           Example: /<command>
  kickall:
    description: Kicks everyone
    usage: |
           /<command> Reason
           Example: /<command> Because i felt like it
  muteall:
    description: Mutes everyone
    usage: |
           /<command> Reason
           Example: /<command> Because i felt like it

  unmuteall:
    description: Unmutes everyone
    usage: |
           /<command> 
           Example: /<command>
  freezeall:
    description: Freezes everyone
    usage: |
           /<command> 
           Example: /<command>
  unfreezeall:
    description: Unfreezes everyone
    usage: |
           /<command> 
           Example: /<command>
  freeze:
    description: Freezes a player
    usage: |
           /<command> name
           Example: /<command> athlavard
  unfreeze:
    description: Unfreezes a player
    usage: |
           /<command> name
           Example: /<command> athlavard
  gatekeeper:
    description: Shows the Gatekeeper information 
    usage: |
           /<command> 
           Example: /<command>